apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.19.6
  name: eksa-gitops-mgmt-nokia-cu2
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 172.16.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 192.168.1.74
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-mgmt-mc-nokia-cu2
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-mgmt-dcc-nokia-cu2
  eksaVersion: v0.19.6
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-nokia-cu2

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-mgmt-dcc-nokia-cu2
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-jammy-eks-anywhere-minimal-amd64-eks-anywhere-1-29-cu-20240917.raw.gz
  tinkerbellIP: 192.168.1.75

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-mgmt-mc-nokia-cu2
  namespace: default
spec:
  hardwareSelector:
    type: mgmt-nokia-cu2
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZQZz/MZ4EX0fwPsJKWeVCFDeDTS/CboRhR7+qwCdXrHczLAkvGL9dFfNsvCKDirlRmZ6W8WXPfKYIkwVXNWWdWqGRtB3Axk1rQJYa53hIf/AIvWEtHJMKqmN+kINf3+pF9HRrHRfe9LfAwOSwaqrmfkiT98J9Ni/kOYN56n+iLMUAsExkSDVQqFL4wpc52VhU8MB0G3HS/H38/8Hxs6o5oymrH5RDrIzXx6zi9N9drbS7xSfaFdyKYA1IMne9D5wWag+a+mtHH+pLFxweJOLy7E52m0+xE5syrIM6nZmuRWDBG5NAFnS8A6G3FfWKjhnRorB3WZAycSpwCJi7U/t/WDOxgQGsDfPQLntq62RFOv33NGE+dJufcbCfKDIpxcv24NMOKcFdF+2Natg9vwkHZdaWEpel52lhvgJp/nisvFE/l7YI00LU8jek6tHKzLp69T3GbpWhLYIXrLvAo6f6K+7cyIMrNosrhotOtda8Lq1Amvqya/uUAQJsv89/fhTN3DVPZJZOD4CWMd+Emg+eSPwAtk4qZ8Q21BAsT5INd0JDg4yogmZM67qbyWaZeJIEeU1BaMHepby8Rr1GT8yL8Mz/MXyO4HKiFE+7qn1qhKhBYnQQdKa2yrqjytjkn5AfkSH43KQTCFuwSQ7IIUl+87WjDD24pzfwCI2m2rOcXQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-nokia-cu2
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
