apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.19.6
  name: eksa-gitops-mgmt-nokia-cu2
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 172.16.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 192.168.1.74
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-mgmt-mc-nokia-cu2
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-mgmt-dcc-nokia-cu2
  eksaVersion: v0.19.6
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-nokia-cu2

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-mgmt-dcc-nokia-cu2
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-jammy-eks-anywhere-minimal-amd64-eks-anywhere-1-29-cu-20240917.raw.gz
  tinkerbellIP: 192.168.1.75

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-mgmt-mc-nokia-cu2
  namespace: default
spec:
  hardwareSelector:
    type: mgmt-nokia-cu2
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDjpil62kNrHtSRLZRmV+jJDd5OekkQ7pjHfTLuwBMFCHM7RdGnshXgDDohA0q4Simm/MheWuUXxoxuC3O3DUIZQ8e+J/5fy0ab7xbeULwHn/3OXULG5ZP8aVQk52AiiKQmogpSPUw3sk0rIkjG+4aE9lTi0Kx+I0SgZofJzKeBVnSAaeuYjexcHN8tvq6p7qGSYcreJhagvsGb7oUtvFXfiRFH2ThQVixM12/nLrmWVKDSsACKuBVankC4ubQI/t98mBZcs8suIzEFdNYMhIWNnSzxF/dAD6jCtEAOACk2+I4RmWhdFIOAcF8MngZ88VoM075X94KJN1ofNAFqhFP7IVL3Zq8SWHeHr5C6USx58Jr7NrlG9FpvH/Jm/tBZZCAC7HD3CdOV+ig6uaS6l0OhhAyCMeyvH5uB381i1jbAEsQHQfUoHbsGGOmTmGWIUmmvanvyfi2Ms+uy0ne6Gt2JaWqtbvey5FGG6K9kAu6R02Irsd1bVymC8GjyxA/tlObqwW1srqL8HDc4vVVYbQK/qIgVMUPVgMxz/E1oC7rGLUsmz4so3vFUhjU6hYvQaZ/XxwR7uDTHEUs9MrplFmZ+OglLFVKJsntLO8uqpLma5BJoqFUHqjtL/UnAtXC+4sp5CK3YE32QZt3G+F/vCd8hfSH4SUr+rGU/soknIjr9rQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-nokia-cu2
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
