apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.19.3
  name: eksa-gitops-mgmt-hpe-lab2
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.45.10.48
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-aio-mc
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-aio-dcc
  eksaVersion: v0.19.3
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-hpe-lab2

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-aio-dcc
  namespace: default
spec:
  hookImagesURLPath: http://10.45.10.30:9900/hook
  osImageURL: http://10.45.10.30:9900/ubuntu-2204-eng-v1.29.0-kernerl-5.15.0-76-generic.gz
  tinkerbellIP: 10.45.10.49

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-aio-mc
  namespace: default
spec:
  hardwareSelector:
    type: mgmt
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCZDo5sjadCxMzy5qn0Vht03OkDF8Oz/1SrNQ/qXq+WW6Bx3s6TJq+iMWKSPjuZ3/IR+yShgXXcW2jUUMK88e+a+UReW51ZtDK5mpg5xngMyg+i7YVovtCLnF8hztvs4jRqpAGMZyFqJ0C+Vxi2O9RPdsFfIuSExSoB+cg6ifQ4Q7GlS9xrhEgzrTOQaA844FdS5MyamIltUzFZxF2NG09k+Zlr1tkJMJpOT5Bm67QyHe0CFA5SO8fGg7srfxWGZhxH+QxJ1xGgydXHvznLbQpiNVSaPVxoBP7/m7XBDkgJj+jHxQjICwFBLkzyrj/l1R758Nab1z6ZW39n44H02x3ybcV8WYM1B5H+61Zy9t2X1hkaDxj3IZ8purMVdGoxnoKThf2zu3kxwg2O9NFhMxZFdtSVfpoZvtaDZfCtJtbIC4JEP4WhbzMiMm/e5EDwHtPFNF33JkEZvg154eR5yAcYBQeiBOx0oOEpEXueTBtAg336rJc4NDbv6P0q5OTdN6Lr8zqQ2fI4VHa8yXJNAWh7ynMM6ZWhh8/NPhihZV9h9ZkZW9lCf9Khh4BlWJE/m07ThUZKU6V1fzoxE3NPK8kbx386cLifm0wo8KOxRwXIaZS8XjyCUBdkqOzUxSPfRuFOiRkV55OhB7cbN3MroNT6PUXp9Gf6mhbb5wQmSohgDQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-hpe-lab2
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
