apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.19.1
  name: eksa-gitops-mgmt-hpe-lab2
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.45.10.48
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-aio-mc
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-aio-dcc
  eksaVersion: v0.19.1
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-hpe-lab2

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-aio-dcc
  namespace: default
spec:
  hookImagesURLPath: http://10.45.10.30:9900/hook
  osImageURL: http://10.45.10.30:9900/ubuntu-2204-eng-v1.29.0-kernerl-5.15.0-76-generic.gz
  tinkerbellIP: 10.45.10.49

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-aio-mc
  namespace: default
spec:
  hardwareSelector:
    type: mgmt
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDO5B7S6PDeTKrWhbc7rL8Er8l/IkjAdF/7S3RfVTExRJsauirmljnQgimdI8+mxMrCQdNFmsDVN+hytshZT6ty1+mYhAN1J5mc3OQVkxTpOe4QtF+EnGlj4KMI2U09w2uSCxv8SbqrXXjywl3VgRez/WO5eZevEEl6jr/VeuZqteIsWyjwKbbzeWURy3FGV1+aeYP02FB0g4nUn/YM/o1Va3/tsjcF6NrVh8y77XopLL+obipwgb+en4hu2P2aJQ8pxPejWbmLh5P62Mvjl1/3UtaM8dfV3ZTMBqtXp9HKGgVPtYq92uhYPWfIKiDV9EG3z3sbK61kqEOgwD9D9tqpkoScU4x/2JRLYfBhiXSbrSpr4zjHSc4ug609IovoiqjgcmRauuC2BvbzW8HseCKNBtplxkT1gmPl2RqpcvNjSrSrAGgLxr7ewOEeD8KhGip+mYbRcb1K4HxJX2KRL4QQNs+Gihqq5DJOMujfg38R+UY3rN65v2wl8EtBOT7P6sx93xrFYSKkLPRLiydH2OY9ycxAtNdCoHTcYUPzZFA2vyDriuj7xYIZRyvDcVR9Q6WVKOrO7+pMT67Q2Svc60NBS/gjjVO80XMPCHxEHwhsa9AcoZk4MjIb0sc/T+U+tWqWDkz65VbJf4hN3vgBWKqTekxkFPMgdn//IWrxaIY8LQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-hpe-lab2
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
