apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eksa-gitops-mgmt-multinode
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 172.16.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 192.168.1.208
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-mgmt-mc
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-mgmt-dcc
  eksaVersion: v0.18.7
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.28"
  machineHealthCheck:
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-multinode

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-mgmt-dcc
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-2204-eng-v1.28.7-kernerl-5.15.0-102-generic.gz
  tinkerbellIP: 192.168.1.209

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-mgmt-mc
  namespace: default
spec:
  hardwareSelector:
    type: mgmt
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCZw/Pzfw2GXBF/VA7rOmH65XvWKQwhMIFr4J42c2MKLsiPs8L69aBTgst9tx45iBzAhaKAAPVc1kmducFU8cxkJQUGJOhwA33Sf51Laja3BYGYXnzhgFAfpAW/Lscde9UypK0NJiziJYI7FqLa03qJQH9YJyefhhHa+skgzQHD5mLmCEVsorENiy8OyFQyReSC9FrfNGCBNlxJmgeWnh1vLqQyG24wQ91LnQCj7CuSBRMsTntp6PLsArxJ0MpfCtiV/R1DMT35IkplcTmxP8hlnGkbdwmZmNxnmpz1vXzoOoE4EyoOO7uKRMFsa0VY2o1xmzhwWIWVbk8CgaRFCzktIImF3WnEEfJPZ9xMO7y4DeWw7nejHMz/ekzZQExZI9vGUYb9WKdMtTp4xoO4yxH7z+dyEBe6IFT7j0rfUwNOgQoIOKauSTwNcZC8zgSbuvF/SruKEirGYfvv8Ik5hV7oSvZ3jNfb0lUdiePBpoEC0j/BMRws6iXd3llyShHZXvxuqpQGxnE0pUiBWpkk8Gpnlh5xh+Kyj8Ix4Zd3K5NgXjFQ382blGVQ1IfO7F0foALKdRsckvSeTfovM/lPfzMBNTg6zUGCha13M8/o+hWwO/6g4T6U0oNgotJL9RBLPse+oWUWV0ETKRrZI+2BRsIProYkZi73ETTvTkjW/aWTMQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-multinode
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
