apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eksa-gitops-mgmt-171
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 192.168.1.66
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-aio-mc
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-aio-dcc
  eksaVersion: v0.18.0
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.26"
  machineHealthCheck:
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-171

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-aio-dcc
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-2204-eng-v1.26.6-kernerl-5.15.0-76-generic.gz
  tinkerbellIP: 192.168.1.67

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-aio-mc
  namespace: default
spec:
  hardwareSelector:
    type: aio
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQz9YubUXL1XC6VjN94cnpahOH9I/6pdPR1cZLXnsQOQCCHlAO1DkOGhvftyNg5OYcr5RPl6M3Gj+Ri2LTgHnQdKNowW/fjdShjtRWQNTIsqRShPyd7f7/sJeSwekekGqc830XUc37Kf18QSCsfGx7gR2pQfC//h33CZpauXVT/Y48blf78KZ8yWP0Fry+r6tIAX4EMM0BR5aMK1X418el0k0KAeaRzB5tmjM4dDBeynQwFKBefEIpBKgtaRv4yR8RAAmB/cU0RCFe0hgf7kLkdRVb5r9qwLyFZMjwxLXP6atwioBNXdeKYDaV4wtBiPrJOfvM+IZrkXiNF/iNS6yebdpOM1iEO/iWDrfx55E4DMeG8H0F0U/WfHkCFyJezSn1OI2AjlrB8r2ITGJWYovBHV9Nz1AzrO1DCCIG2jpFhZ8dPYo+Nd0neKjAsd86DLlf6KOE7ETKKJIFk8S3XvPFhBcWO9OQtAc9ReAdxgafA/dR5rBPz5sAPRCsan1Qy7UOKxFY+OlV6R8cc6KIQ2hHYdg47gLh0sQA2kVfsQ3xTVstGtey9D0Kh3k2981aqBOiYRq7TsEEWuBecF8mSi384c/L1oeEg4u56qX2tef/4RO+E1vkODK/9VcMnzMqaPUKxJQxYIKDXysBCKE66Cri7+JIfbVVoJEm4Zc8pMIHVQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-171
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
