apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eksa-gitops-mgmt-171
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 192.168.1.66
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-aio-mc
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-aio-dcc
  eksaVersion: v0.18.7
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.28"
  machineHealthCheck:
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-171

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-aio-dcc
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-2204-eng-v1.28.7-kernerl-5.15.0-102-generic.gz
  tinkerbellIP: 192.168.1.67

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-aio-mc
  namespace: default
spec:
  hardwareSelector:
    type: aio
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfgxHuDGrNN2BSIGRsgYAvcKdshzBmHP8QhFMgr1F4rFeu8x57jemEp0x7DSX3BKqyqzOpaDOc75H/uHEqvimP8NE21przt72VG2NtRByT6M2JiWzLRPzdgddaRX071Vsb4OsivRPWQIkEHZTk7TF4lb5Sp62eLa8jRBmBwwTlDEwvlMquAcpmT92yZgp181F0BTof3lfCVGZZyv071vhiOGayQs4zNuU78atE9mKzbyeBEWZGY9riG4AEvYwqyOCCiQKhyVq4SxU/jkMxiYri3B/Jpc+7GBEwnqbxJjuFxd+IgcCgitenrr+b2xvoX8jWmvFEYy0k+JIttMndMTIp3Njy+5vW1Kxdiv0zJ16515Qeld0BUPZOAAOMnCUhMh8l5T0mVVzFz7a9ybavXpX1RmBYQb9ZtBPcV7ikTUYbPYZSkg/E777XA3fjf36AwNJpVvMjzXDYMp0bvna1D2/Xi/wAWHiBxMGTYmEzetbdVEe5SW6QWZELTnouXIihLMBXtdbUKFfdtCH6jXWhpz8vOWd8FFpnf9oWIRfgZmIb84GCbb8dkbKf1hJiFX6ubL2doexg+tcNXhdpxBBxiph1gljsdw0Lod6nA71ea/BREozwdbanVxUrceFjP7wwB96O7XR7PgE6zNEVdFWp/1duYBUTMEKCTeYCt/Zvch6gjQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-171
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
