---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: observability
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      version: 25.21.0
  interval: 1m0s
  releaseName: prometheus-release
  values:
    prometheus-node-exporter:
      extraArgs:
      - --collector.processes
      - --collector.tcpstat
      - --collector.systemd
    server:
      persistentVolume:
        storageClass: prometheus-storage-class
      global:
        external_labels:
          cluster: eksa-gitops-workload-172-sn
      remoteWrite:
      - url: http://3.15.228.137:31000/api/v1/write
    alertmanager:
      persistentVolume:
        storageClass: alertmanager-storage-class
  install:
    disableWait: true
