apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.19.6
  name: eksa-gitops-mgmt-nokia
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 172.16.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 192.168.1.213
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-mgmt-mc-nokia
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-mgmt-dcc-nokia
  eksaVersion: v0.19.6
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-nokia

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-mgmt-dcc-nokia
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-jammy-eks-anywhere-minimal-amd64-eks-anywhere-1-29-20240903.raw.gz
  tinkerbellIP: 192.168.1.214

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-mgmt-mc-nokia
  namespace: default
spec:
  hardwareSelector:
    type: mgmt-nokia
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdQLa50O6W0Oth6JOnIc/Q6a4xTskHMmmBcXZ3840yrjmMJBapaK8tRk84NDb2AXCNrJ39ilzfFfQF7VuuBHjiEVOpGpc/+uOJuYFJKexsEJp1tcGHWDFlUqI7ixJ9oK2qyVcsIoTkqk9QXTXizJINxffSJ65o6FQRpt796/JCQ7mEECZvq1GK17K8w+9cgSzgAYdBrqoB3m12nJD3aSwFbgzBsk4nEEdPLknjEbNCMLlpvCVhVR4vH+iWOjOQbEJ33KIWVofS5H6HZ4CP0o0k/vV3BeMXqlRdnLsGPTcPGwltWdkhNy+NfUg1grCZ7lLiffFg0zJAygREtaCFxaU4TnAOMcJdkfFU+p1uU+f8fcYQ7sI5brMYmW11kchspvx694WjtlXEpECbncQ3vb9xAo41t5/QhYETCOOWo69qCUQnHBYVvHq5yEay+xDFPrbZOOsx56keb5bT2L6T22Gjv2YM5Z/FCx/Y/ym3lK2FOPXykwCDBjEGHl6hrKImjgGt5durTZQhsC1aOctqh3pFbCsvi0KQ5XbwLv4pMPR7rCbwdk37h0CeKtybQruc1gsvIy7OqyLE2pBN6S24BdZRDUW3iAIX+WAf17LSypz1I/ZTnE/gYAiV1s0drSq+geqNXom+pLKD9jaPO6puzklZ7nBFCX8c6UjSgF6Kvo94FQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-nokia
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
