apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.19.6
  name: eksa-gitops-mgmt-nokia
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 172.16.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 192.168.1.213
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-mgmt-mc-nokia
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-mgmt-dcc-nokia
  eksaVersion: v0.19.6
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-gitops-mgmt-nokia

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-mgmt-dcc-nokia
  namespace: default
spec:
  hookImagesURLPath: http://192.168.1.80:9900/hook
  osImageURL: http://192.168.1.80:9900/ubuntu-jammy-eks-anywhere-minimal-amd64-eks-anywhere-1-29-20250314.raw.gz
  tinkerbellIP: 192.168.1.214

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-mgmt-mc-nokia
  namespace: default
spec:
  hardwareSelector:
    type: mgmt-nokia
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUuLssOZJ3uhp/ZRrEBnugH+KBTldJmip8RGEXY6AG6TPS9JoBrQkq4rR7jMupmfEHTuGb7WQg0kf8SlW4pJiAwQzMdPkKOAk1zoYwLP/Fo4MdbP6vlXToMKNc3gQt0n692vUEPUyl+/nPoWvOxpzSfoe+PGe6wz0wXzUCvVYyy5GU9+TNbMdD8dqW1vwXsHppkG9s7lrB3g7KEIdYRp+ZiDNrqwr8X80dGy4HrSSsJBtRTiljPCcJnF54PrRccXbL8xuRJqd48uWo/pt4uS2aQ5AN+YRtKSD0IamwBVIH96X+olU+dov+m2lYbBj4BJ9LVMunM+Jgelkt65HHlmUG2hYPmeALCwQudYSm2FtjUJnsQwi+OpSx7wnS+hVGHUDkWiEs+Hg14MRE6XZgwQOco6xLeOt9rj3rcs7W3WDPFuU455ZuhSEIcxXGhG0M+Sp+VC12+9N3+TXrzShjLV9sQVZ6dQwW7MoJSMVWvfXETh63wAbMore1T9yPYmafFvrdDEh0gE7omQ2j+zMsumB9H5hitWTurA6wD/GcYYQx9C6M6EX5FXpj+taX6XrZVhe8b96NE+JQmwRdAZlciv5kJ2/VXFCaZs9Arb25Df8JBFSVja7LcgNAWY7xNFD47tLTVjhvkqkwmtZHQvvYLq5fKQmWieZjuxxyVkI+ZJf7ww==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-gitops-mgmt-nokia
  github:
    owner: Cheng-Ian-Liu
    personal: true
    repository: eks-a-gitops
  systemNamespace: flux-system

---
